### ISSUE TITLE
When running "train. Py", there is a problem on line 132 of the "model. Py" file:

### ISSUE THREAD

**Issue by redsoup** [cvlab-yonsei/LbA#5]
When running "train. Py", there is a problem on line（loss = torch.mean(comask_pos * self.criterion(feat, feat_recon_pos, feat_recon_neg))） 132 of the "model. Py" file:
Traceback：RuntimeError: The size of tensor a (9) must match the size of tensor b (18) at non-singleton dimension 3

**Comment by sanghoooon** [comment]
Hello. Thank you for reaching out. 
Your issue seems to be deprecated in #4 .

Check whether your PyTorch version is 1.7.1, or use our provided Dockerfile (even better). 
For other PyTorch versions, I recommend reshaping input tensors to `nn.TripletMarginLoss`.

Let me know if you have any further problems by re-opening this issue.
